
const $=s=>document.querySelector(s);let coords=null,chosen=new Set(),lastResults=[],wheelAngle=0,spinning=false;
const names={italian:'Italian',japanese:'Japanese',thai:'Thai',indian:'Indian',mexican:'Mexican',chinese:'Chinese',korean:'Korean',pizza:'Pizza'};
$('#distance').addEventListener('input',e=>$('#distanceVal').textContent=e.target.value);
document.querySelectorAll('.chip').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.cuisine==='all')));
$('#cuisines').addEventListener('click',e=>{const b=e.target.closest('.chip');if(!b)return;const value=b.dataset.cuisine;if(value==='all')chosen.clear();else if(chosen.has(value))chosen.delete(value);else chosen.add(value);document.querySelectorAll('.chip').forEach(x=>{const active=x.dataset.cuisine==='all'?chosen.size===0:chosen.has(x.dataset.cuisine);x.classList.toggle('active',active);x.setAttribute('aria-pressed',String(active))})});
function setStatus(s){$('#status').textContent=s}
$('#locBtn').onclick=()=>{if(!navigator.geolocation){setStatus('Geolocation isn’t available in this browser.');return}setStatus('Finding your location…');navigator.geolocation.getCurrentPosition(p=>{coords={lat:p.coords.latitude,lon:p.coords.longitude};$('#locationText').textContent=`${coords.lat.toFixed(4)}°, ${coords.lon.toFixed(4)}° · ready to search`;$('#locBtn').textContent='Ready';setStatus('Location found. Let’s find somewhere good.')},e=>setStatus(e.code===1?'Allow location access to find nearby restaurants.':'Couldn’t get your location. Check your device settings.'),{enableHighAccuracy:false,timeout:12000,maximumAge:300000})};
function cuisineOf(tags){return String(tags.cuisine||tags['cuisine:en']||'').toLowerCase().replaceAll('_',' ')}
function humanCuisine(tags){let c=cuisineOf(tags);if(!c)return 'Restaurant';return c.split(/[;,]/)[0].replace(/\b\w/g,x=>x.toUpperCase())}
async function findPlaces(options){
 const {km,origin,cuisines,onlyOpen,excludeFastFood,now}=options;
 // Any driving route within km must also fall within this straight-line radius.
 const query=`[out:json][timeout:25];nwr[amenity~"^(restaurant|fast_food|food_court)$"](around:${km*1000},${origin.lat},${origin.lon});out center tags;`;
 let data;
 for(const endpoint of ['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter','https://overpass.private.coffee/api/interpreter']){
  try{const response=await fetch(endpoint,{method:'POST',body:query,signal:AbortSignal.timeout(30000)});if(!response.ok)continue;const result=await response.json();if(Array.isArray(result.elements)&&!result.remark){data=result;break}}catch{}
 }
 if(!data)throw Error('Could not complete the restaurant search. Check your connection and try again.');
 let places=data.elements.map(x=>({id:`${x.type}/${x.id}`,name:x.tags?.name,lat:x.lat??x.center?.lat,lon:x.lon??x.center?.lon,tags:x.tags||{}})).filter(x=>x.name&&Number.isFinite(x.lat)&&Number.isFinite(x.lon)&&(!excludeFastFood||x.tags.amenity!=='fast_food')&&TableTurn.matchesCuisine(x.tags,cuisines)&&(!onlyOpen||TableTurn.openState(x.tags.opening_hours,now)===true));
 const seen=new Set();places=places.filter(x=>{const key=`${x.name.toLowerCase()}|${x.lat.toFixed(4)}|${x.lon.toFixed(4)}`;if(seen.has(key))return false;seen.add(key);return true});
 places.sort((a,b)=>distance(origin,a)-distance(origin,b));
 places=places.map(x=>({...x,driveKm:distance(origin,x)*1.35,estimated:true,minutes:distance(origin,x)*1.35/35*60}));
 const routed=[];
 for(let offset=0;offset<places.length;offset+=40){
  const batch=places.slice(offset,offset+40);setStatus(`Checking driving distances: ${Math.min(offset+40,places.length)} of ${places.length}…`);
  let table=null;
  try{const dest=batch.map(x=>`${x.lon},${x.lat}`).join(';');const response=await fetch(`https://router.project-osrm.org/table/v1/driving/${origin.lon},${origin.lat};${dest}?sources=0&annotations=distance,duration`,{signal:AbortSignal.timeout(10000)});if(response.ok)table=await response.json()}catch{}
  routed.push(...TableTurn.applyRoutes(batch,table,km));
 }
 return routed;
}
function distance(a,b){const r=6371,d1=(b.lat-a.lat)*Math.PI/180,d2=(b.lon-a.lon)*Math.PI/180,A=Math.sin(d1/2)**2+Math.cos(a.lat*Math.PI/180)*Math.cos(b.lat*Math.PI/180)*Math.sin(d2/2)**2;return 2*r*Math.asin(Math.sqrt(A))}
const foodIdeas={italian:[['House-made pasta','A comforting classic'],['Margherita pizza','Simple, done beautifully'],['Tiramisu','Save room for dessert']],japanese:[['Chef’s sushi selection','A little bit of everything'],['Tonkotsu ramen','Rich broth, good noodles'],['Karaage chicken','Crispy and comforting']],thai:[['Pad see ew','Smoky wok-fried noodles'],['Green curry','Fragrant, creamy, just right'],['Mango sticky rice','A sweet finish']],indian:[['Butter chicken','Rich, spiced and loved'],['Paneer tikka','Smoky and satisfying'],['Garlic naan','Always order extra']],mexican:[['Tacos al pastor','Sweet, savoury, bright'],['Quesadilla','Golden, melty comfort'],['Churros','A little cinnamon sugar']],chinese:[['Mapo tofu','Bold and warming'],['Dan dan noodles','A tangle of savoury heat'],['Scallion pancakes','Crisp, flaky, shareable']],korean:[['Bibimbap','A little of everything'],['Korean fried chicken','Crunchy, sticky, joyful'],['Tteokbokki','Chewy rice cakes, big flavour']],pizza:[['Margherita','The perfect starting point'],['Pepperoni','A reliable favourite'],['Garlic knots','For the table']]};
function foodFor(c){const list=foodIdeas[c]||[['Chef’s favourite','Let the kitchen surprise you'],['Something seasonal','Ask what’s good today'],['A little treat','You deserve dessert']];const shuffled=[...list];for(let i=shuffled.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[shuffled[i],shuffled[j]]=[shuffled[j],shuffled[i]]}return shuffled.slice(0,2)}
function showWheel(){document.querySelector('.hero').style.display='none';document.querySelector('.main').style.display='none';$('#wheelScreen').classList.add('active');window.scrollTo({top:0,behavior:'smooth'});$('#wheelWinner').classList.remove('show');drawWheel(0);$('#wheelCount').textContent=`${lastResults.length} restaurant${lastResults.length===1?'':'s'} on the wheel`}
function drawWheel(rotation=wheelAngle){const canvas=$('#wheel'),ctx=canvas.getContext('2d'),n=lastResults.length,size=canvas.width,c=size/2,r=c-14,slice=Math.PI*2/n,palette=['#315b43','#d6ed83','#e7a47b','#94ad85','#dbd5b9','#b8c99f','#d98562','#e7bd76','#739078','#e9e7dc'];ctx.clearRect(0,0,size,size);ctx.save();ctx.translate(c,c);ctx.rotate(rotation);for(let i=0;i<n;i++){const start=-Math.PI/2+i*slice;ctx.beginPath();ctx.moveTo(0,0);ctx.arc(0,0,r,start,start+slice);ctx.closePath();ctx.fillStyle=palette[i%palette.length];ctx.fill();ctx.strokeStyle='#fffefa';ctx.lineWidth=4;ctx.stroke();ctx.save();ctx.rotate(start+slice/2);ctx.textAlign='right';ctx.textBaseline='middle';ctx.fillStyle=['#fffefa','#283322','#3b332b','#fffefa','#37382f'][i%5];ctx.font=`600 ${Math.max(16,Math.min(24,210/n))}px DM Sans, sans-serif`;let label=lastResults[i].name;if(label.length>21)label=label.slice(0,19)+'…';ctx.fillText(label,r-28,0);ctx.restore()}ctx.restore()}
function showWinner(place){const menu=TableTurn.menuLink(place);$('#foodPhotosLink').href=TableTurn.foodPhotosLink(place);$('#menuLink').href=menu.href;$('#menuLink').textContent=menu.label;$('#menuNote').textContent=menu.note;const c=Object.keys(names).find(x=>humanCuisine(place.tags).toLowerCase().includes(x))||'',foods=$('#foodToggle').checked?foodFor(c):[];$('#winnerName').textContent=place.name;$('#winnerMeta').textContent=`${humanCuisine(place.tags)} · ${place.estimated?'Estimated ':''}${place.driveKm?place.driveKm.toFixed(1)+' km drive':distance(coords,place).toFixed(1)+' km away'}${place.minutes?' · '+Math.round(place.minutes)+' min':''}`;$('#wheelFood').innerHTML=foods.length?`<strong>Dish ideas: ${foods[0][0]}</strong><div>${foods[1][0]}</div><div>Based on cuisine, not this restaurant’s menu. Check availability and dietary needs with the venue.</div>`:'';$('#directionsLink').href=`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(place.lat+','+place.lon)}&travelmode=driving`;$('#wheelWinner').classList.add('show')}
function spinWheel(){if(spinning||!lastResults.length)return;spinning=true;$('#spinBtn').disabled=true;$('#spinBtn').textContent='Spinning…';$('#wheelWinner').classList.remove('show');const n=lastResults.length,index=Math.floor(Math.random()*n),slice=Math.PI*2/n;let start=wheelAngle%(Math.PI*2);if(start<0)start+=Math.PI*2;let target=-(index+.5)*slice;target=((target%(Math.PI*2))+Math.PI*2)%(Math.PI*2);let delta=target-start;if(delta<0)delta+=Math.PI*2;const final=wheelAngle+Math.PI*2*(5+Math.floor(Math.random()*3))+delta;const from=wheelAngle,t0=performance.now(),duration=window.matchMedia('(prefers-reduced-motion: reduce)').matches?1:4700;function frame(now){let t=Math.min(1,(now-t0)/duration),ease=1-Math.pow(1-t,5);wheelAngle=from+(final-from)*ease;drawWheel();if(t<1)requestAnimationFrame(frame);else{wheelAngle=final;drawWheel();spinning=false;$('#spinBtn').disabled=false;$('#spinBtn').textContent='Spin again';showWinner(lastResults[index])}}requestAnimationFrame(frame)}
$('#spinBtn').onclick=spinWheel;$('#backBtn').onclick=()=>{if(spinning)return;$('#wheelScreen').classList.remove('active');document.querySelector('.hero').style.display='';document.querySelector('.main').style.display='';window.scrollTo({top:0,behavior:'smooth'})};
$('#pickBtn').onclick=async()=>{if(!coords){setStatus('Tap “Detect” first so we can search near you.');return}const options={km:Number($('#distance').value),origin:{...coords},cuisines:new Set(chosen),onlyOpen:$('#openToggle').checked,excludeFastFood:$('#excludeFastFoodToggle').checked,now:new Date()};const controls=[...document.querySelectorAll('.config button,.config input')];controls.forEach(x=>x.disabled=true);const btn=$('#pickBtn');btn.querySelector('span').textContent='Looking nearby…';setStatus('Finding places and checking drive times…');try{lastResults=await findPlaces(options);if(!lastResults.length){setStatus('No matching restaurants found in that distance. Try a wider radius or another cuisine.');return}wheelAngle=0;showWheel();spinWheel()}catch(e){setStatus(e.message||'Couldn’t load nearby places. Please try again.')}finally{controls.forEach(x=>x.disabled=false);btn.querySelector('span').textContent='Find my dinner'}};
